---
title: "Overview"
author: "Altan"
date: "August 1, 2015"
output: html_document
---
```{r, echo=FALSE}
library(knitr)
library(iterators)
library(magrittr)
library(dplyr)
library(tidyr)
library(foreach)

# Load metadata
fmeta <- tbl_df(read.delim('data/meta.txt', stringsAsFactors = FALSE, fileEncoding = "UTF-8"))
labels = unique(select(fmeta, Label))

# Load frequency tables
frequencies <- foreach(x = iter(fmeta, by='row'),
        .combine = rbind
        ) %do% {
            tbl_df(read.delim(x$FrequencyPath, stringsAsFactors = FALSE, fileEncoding="UTF-8"))  %>%
            arrange(Target, desc(n), Assoc) %>%
            mutate(Label = x$Label) %>%
            group_by(Label, Target) %>%
            mutate(Rank = dense_rank(desc(n)), 
                   RankMax=rank(n, ties.method = "max"),
                   Probability=round((1/(sum(n)/n)), 3)
            )
}


# Calculate set sizes
setsizes <- foreach(x = iter(fmeta, by='row'),
                    .combine = rbind
                    ) %do% {
                      frequencies %>% filter(Label == x$Label, n > 1, Assoc != '?') %>%
                      group_by(Target) %>%
                        summarise(SetSize=n()) %>%
                        mutate(Label = x$Label)
}



# Calculate set size statistics

MeanSetSizes <- foreach(x = iter(fmeta, by='row')) %do% {
  setsizes %>% filter(Label == x$Label) %>% summarise(round(mean(SetSize), 2))
}
MedianSetSizes <- foreach(x = iter(fmeta, by='row')) %do% {
  setsizes %>% filter(Label == x$Label) %>% summarise(round(median(SetSize), 2))
}
SetSizeSDs <- foreach(x = iter(fmeta, by='row')) %do% {
  setsizes %>% filter(Label == x$Label) %>% summarise(round(sd(SetSize), 2))
}

fmeta$MeanSetSize <- as.vector(MeanSetSizes)
fmeta$MedianSetSize <- as.vector(MedianSetSizes)
fmeta$SetSizeSD <- as.vector(SetSizeSDs)

```

# Data Sets
```{r, echo=FALSE}
kable(select(fmeta, Label, Description, Year, Subjects))
```

## Set Size Info
```{r, echo=FALSE}
kable(select(fmeta, Label, MeanSetSize, MedianSetSize, SetSizeSD))
ss <- spread(setsizes, Label, SetSize)
kable(ss)
```

-------------

## Target Info
```{r, echo=FALSE}

targets <- unique(select(setsizes, Target))
ttables <- foreach(t = iter(targets, by='row')) %do% {
  foreach(m = iter(fmeta, by='row')) %do% {
   filter(frequencies, Label==m$Label, Target==t$Target, n > 1) %>% top_n(n, n = 3) %>% ungroup() %>% arrange(Label, Target, desc(n), Assoc)
    }
}
ttables <- unlist(ttables, recursive = FALSE)
```

```{r, echo=FALSE, results='asis'}
for (i in 1:length(ttables)) {
    print(kable(ttables[[i]]))
}


```

