---
title: "New Associates"
date: "August 17, 2015"
output: 
  html_document: 
    fig_caption: yes
    number_sections: no
    theme: spacelab
    toc: no
---
```{r, echo=FALSE, results="hide", error=FALSE, warning=FALSE, message=FALSE}
library(knitr)
library(iterators)
library(foreach)
library(ggplot2)
library(GGally)
library(pastecs)
library(DT)
library(ez)

source("../serca.R")

set_os_locales()
```

[Back to Overview](overview.html)


```{r NewWordsInit, echo=FALSE, cache=FALSE}
#news <- tbl_df(read.delim('../data/new_words.txt', stringsAsFactors = T, fileEncoding="UTF-8"))
frequencies <- tbl_df(read.delim('../data/frequencies.txt', stringsAsFactors = TRUE, fileEncoding="UTF-8"))
asets <- frequencies %>% filter(Assoc != '?', n > 1)
asets.tem <- asets %>% filter(Label=='tem')
news <- asets %>% filter(Label != 'tem') %>% anti_join(asets.tem, by=c('Target', 'Assoc'))

fni <- frequencies %>% filter(n > 1, Assoc != '?')
distincts <- fni %>% group_by(Target) %>% distinct(Assoc)

```


# New Associates (non-idiosyncratic)
```{r NewWordsDesc, echo=FALSE, cache=FALSE}
new.umi <- news %>% filter(n.umi > 1) %>% select(Target, Assoc, n=n.umi, Probability=p.umi)
new.onl <- news %>% filter(n.onl > 1) %>% select(Target, Assoc, n=n.onl, Probability=p.onl)

new.umi <- new.umi %>% group_by(Target) %>% summarise(Count=n()) %>% select(New.Umi = Count)
new.onl <- new.onl %>% group_by(Target) %>% summarise(Count=n()) %>% select(New.Onl = Count)
kable(cbind(stat.desc(new.onl), stat.desc(new.umi)), digits=2)
news %>% group_by(Label, Target) %>% summarise(N=n()) %>% spread(Label, N, fill = 0) %>% select(-Target) %>% cor
```


```{r NewWordsTable, echo=FALSE, cache=FALSE}
news <- tbl_df(read.delim('../data/new_words.txt', stringsAsFactors = T, fileEncoding="UTF-8"))
news %>% group_by(Label, Target) %>% summarise(N=n()) %>% spread(Label, N, fill = 0)
DT::datatable(news)
```


[Back to Overview](overview.html)
