---
title: "Overview"
date: "August 1, 2015"
output: 
  html_document: 
    fig_caption: yes
    keep_md: yes
    number_sections: yes
    theme: readable
    toc: yes
---
```{r, echo=FALSE, results="hide", error=FALSE, warning=FALSE, message=FALSE}
library(knitr)
library(iterators)
library(foreach)
library(ggplot2)
library(GGally)
library(DT)
library(ez)
source("serca.R")


set_os_locales()
meta <- load_meta('data/datasets.txt')

frequencies <- tbl_df(read.delim('data/frequencies.txt', stringsAsFactors = FALSE, fileEncoding="UTF-8"))
setsizes <- tbl_df(read.delim('data/setsizes.txt', stringsAsFactors = FALSE, fileEncoding="UTF-8"))
setsizesStats <- tbl_df(read.delim('data/setsizes_stats.txt', stringsAsFactors = FALSE, fileEncoding="UTF-8"))

```

# Data Sets
```{r DataSets, echo=FALSE}
kable(select(meta, -FrequencyPath))
```

[Reliability](Reliability.html)
[New Words](new_words.html)
[Set Sizes](set_sizes.html)

-------


## Set Size Info
Values are for associative set size (not blank & not idiosyncratic)
```{r SetSizesStats, echo=FALSE, cache=TRUE}
kable(setsizesStats)
```


Below are the set sizes for each target. Use the search box to find a specific target.

```{r SetSizeTable, echo=FALSE}
ss <- setsizes %>% select(Label, Target, SetSize) %>% spread(Label, SetSize)
DT::datatable(ss)
```


-------


(Associative) Set size: number of different words provided as responses to a target word. Responses that are idiosyncratic are not counted as part of associative set size. So only responses coming from 2 or more participants consititute a word’s associative set size.


```{r SetSizeCor, echo=FALSE, cache=TRUE}
ggpairs(ss %>% select(umi, onl, tem), title = "Reliability for set size - correlation")

```

## ANOVA
```{r AnovaTop6, echo=FALSE, cache=TRUE, warning=FALSE}
#top6 <- do_anova_top6(frequencies)
#print(summary(top6))
t <- frequencies %>% 
    filter(Rank <= 6) %>%
    group_by(Label, Target) %>%
    filter(row_number() <= 6) %>%
    mutate(RowNo = row_number()) %>%
    ungroup() %>%
    arrange(Target, Label, desc(Probability)) %>%
    select(RowNo, Label, Target, Probability)

t <- t %>% group_by(Label, Target) %>% mutate(Wid=paste(Label, Target, sep='.'))

t$RowNo <- factor(t$RowNo)
t$Label <- factor(t$Label)
t$Target <- factor(t$Target)
t$Wid <- factor(t$Wid)
top6.anova <- ezANOVA(data=as.data.frame(t),dv=Probability, wid=.(Wid), within_full=.(RowNo), between = .(Label), detailed=F, type = 2)

print(top6.anova)
  
```


-------



