---
title: "Set Sizes"
date: "August 17, 2015"
output: 
  html_document: 
    fig_caption: yes
    number_sections: no
    theme: spacelab
    toc: yes
---
```{r, echo=FALSE, results="hide", error=FALSE, warning=FALSE, message=FALSE}

library(multcomp)
library(compute.es)
library(pastecs)

library(knitr)
library(tidyr)
library(dplyr)
library(lsr)
library(GGally)

frequencies <- tbl_df(read.delim('../data/frequencies.txt', stringsAsFactors = TRUE, fileEncoding="UTF-8"))
setsizes <- frequencies %>% filter(n > 1, Assoc != '?') %>% group_by(Label, Target) %>% summarise(SetSize=n()) %>% arrange(Target, Label)
idios <- frequencies %>% filter(n == 1, Assoc != '?') %>% group_by(Label, Target) %>% summarise(Idio=n()) %>% arrange(Target, Label)
blanks <- frequencies %>% filter(Assoc == '?') %>% group_by(Label, Target) %>% summarise(Blank=n()) %>% arrange(Target, Label)
setsizes <- setsizes %>% left_join(idios)
setsizes <- setsizes %>% left_join(blanks)
setsizes <- setsizes %>% replace(is.na(.), 0)
setsizes <- setsizes %>% mutate(AssocRatio=SetSize/(SetSize+Idio+Blank))
setsizes <- setsizes %>% arrange(Target, Label, SetSize)




```

[Back to Overview](overview.html)

## Set Size Stats
Values are for associative set size (not blank & not idiosyncratic)
```{r SetSizesStats, echo=FALSE, cache=FALSE}


setsize.stats <- setsizes %>% select(Label, Target, SetSize) %>% spread(Label, SetSize) %>% select(-Target) %>% stat.desc() %>% round(2)
kable(setsize.stats)

assocratio.stats <- setsizes %>% select(Label, Target, AssocRatio) %>% spread(Label, AssocRatio) %>% select(-Target) %>% stat.desc() %>% round(2)
kable(assocratio.stats)

```

## Set Sizes by Target
Below are the set sizes for each target. Use the search box to find a specific target.

```{r SetSizeTable, echo=FALSE}
setsizes.spread <- setsizes %>% select(Label, Target, SetSize) %>% spread(Label, SetSize)
DT::datatable(setsizes.spread)
```

## Set Size Reliability

```{r SetSizeCor, echo=FALSE, cache=FALSE}
ggpairs(setsizes.spread %>% select(umi, onl, tem), title = "Reliability for set size - correlation", diag=list(continuous='density'), lower=list(continuous='smooth'), upper=list(continuous='cor'))
kable(cor(setsizes.spread %>% select(umi, onl, tem)), digits = 2)
```

## Set Size ANOVA

```{r SetSizeAnova, echo=FALSE, cache=FALSE}
a <- aov(SetSize ~ Label, setsizes)
print(formula(a))
print(summary.lm(a))
print(sprintf("R squared: %.2f / Adjusted R squared: %.2f", summary.lm(a)$r.squared, summary.lm(a)$adj.r.squared))
print(etaSquared(a))
a.Tukey <- glht(a, linfct = mcp(Label = "Tukey"))
print(summary(a.Tukey))
print(confint(a.Tukey))

stat.onl <- as.list(setsize.stats$onl)
names(stat.onl) <- rownames(setsize.stats)

stat.umi <- as.list(setsize.stats$umi)
names(stat.umi) <- rownames(setsize.stats)

stat.tem <- as.list(setsize.stats$tem)
names(stat.tem) <- rownames(setsize.stats)

extract.d <- function(m) {
  d <- list()
  d$d <- m$d
  d$var <- m$var.d
  d$ci95 <- c(lower=m$l.d, upper=m$u.d)
  return (d)
}

d.onl.umi <- extract.d(mes(stat.onl$mean, stat.umi$mean, stat.onl$std.dev, stat.umi$std.dev, stat.onl$nbr.val, stat.umi$nbr.val, verbose = FALSE))
d.onl.tem <- extract.d(mes(stat.onl$mean, stat.tem$mean, stat.onl$std.dev, stat.tem$std.dev, stat.onl$nbr.val, stat.tem$nbr.val, verbose = FALSE))

print("Cohen's d for onl-umi")
print(d.onl.umi)
print("Cohen's d for onl-tem")
print(d.onl.tem)



setsizes <- setsizes %>% rename(Set=Label)
levels(setsizes$Set) <- list(`TS`="tem", `Lab`="umi", `Online`="onl")
ss.aov <- aov(log(SetSize) ~ Set, setsizes)
ss.tuk <- glht(ss.aov, linfct=mcp(Set="Tukey"))
ss.ci <- confint(ss.tuk)
ggplot(ss.ci, aes(lhs, estimate)) + geom_linerange(aes(ymin = lwr, ymax=upr), data=ss.ci) + geom_point(aes(size=p), data=summary(ss.tuk)) + geom_point(shape=4, size=6) + geom_errorbar(aes(ymin=lwr, ymax=upr), width=0.25, data=ss.ci) + scale_size(trans="reverse") + geom_hline(linetype="dashed") +  theme_bw() + xlab("Data Sets") + ylab("Estimated mean difference") +
    theme(plot.title=element_text(face="bold", size=14), panel.grid.major=element_blank(), panel.grid.minor=element_blank()) + ggtitle('Multiple comparisons of mean set size') + coord_flip() + theme(aspect.ratio=240/640)

ggplot(data=setsizes, aes(x=SetSize, group=Set)) +  scale_linetype_discrete()+ geom_line(stat="density", na.rm = TRUE, aes(linetype=Set, y=..count..), fill=NA) + theme_bw() + theme(plot.title=element_text(face="bold", size=14), panel.grid.major=element_blank(), panel.grid.minor=element_blank()) + ggtitle('Distribution of set sizes') + xlab("Set Size") + ylab("Count") +  theme(aspect.ratio=240/640)

                                                                                                                                                                                                                                                                                                                                                                         
```

[Back to Overview](overview.html)
